# Exported from Render on 2025-07-25T11:43:25Z
services:
  - type: web
    name: Order-panel-backend
    runtime: node
    repo: https://github.com/harshdevelopes/Order-panel-backend
    plan: free
    rootDir: ./
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.com
      - key: DB_HOST
        fromDatabase:
          name: order-panel-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: order-panel-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: order-panel-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: order-panel-db
          property: password
      - key: DATABASE_URL
        fromDatabase:
          name: order-panel-db
          property: connectionString
    region: oregon
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: order-panel-db
    databaseName: order_panel
    user: order_panel_user
    plan: free
    region: oregon
