# Exported from Render on 2025-07-25T11:43:25Z
services:
  - type: web
    name: Order-panel-backend
    runtime: node
    repo: https://github.com/Dhrumil09/Order-panel-backend
    plan: free
    envVars:
      - key: CORS_ORIGIN
        sync: false
      - key: RATE_LIMIT_MAX_REQUESTS
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_HOST
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        sync: false
      - key: PORT
        sync: false
    region: oregon
    buildCommand: npm install
    startCommand: node dist/index.js
    healthCheckPath: /health
    autoDeployTrigger: commit
version: "1"
