services:
  - type: web
    name: order-panel-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node start.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: CORS_ORIGIN
        value: https://your-frontend-domain.com
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: order-panel-db
    databaseName: order_panel
    user: order_panel_user
    plan: free
